name:                d64-uuid
version:             0.1.0.0
github:              "grmble/d64-uuid"
license:             MIT
license-file:        LICENSE
author:              "Juergen Gmeiner"
maintainer:          "spamless.juergen@gmail.com"
copyright:           "(c) 2018, 2019 Juergen Gmeiner"

extra-source-files:
- README.md


description:         Please see the README on Github at <https://github.com/grmble/thunderbuns#readme>

# base 4.10 is stack lts 10 aka GHC 8.2.2
dependencies:
- base >= 4.10 && < 5
- aeson
- bytestring
- cereal
- d64
- mtl
- uuid
- text
- time

# cereal, aeson only needed for typeclasses


library:
  source-dirs: src

tests:
  d64-uuid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d64-uuid
    - hspec
    - QuickCheck


#
# ghc options and default extensions ... see
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
#

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
